version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: nexora
    main: ./main.go
    binary: nexora
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/Nexora-Inc-AFNOOR-LLC-DBA-NEXORA-INC/nexora-cli/internal/version.Version={{.Version}}
      - -X github.com/Nexora-Inc-AFNOOR-LLC-DBA-NEXORA-INC/nexora-cli/internal/version.Commit={{.Commit}}
      - -X github.com/Nexora-Inc-AFNOOR-LLC-DBA-NEXORA-INC/nexora-cli/internal/version.BuildDate={{.Date}}

archives:
  - id: nexora
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

sboms:
  - artifacts: archive
    args: ["$artifact", "--output", "spdx-json=$document"]
    documents:
      - "${artifact}.spdx.json"

signs:
  - cmd: cosign
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"
